config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en/ do
    devise_for :users, :controllers => { registrations: 'registrations' }, skip: :omniauth_callbacks

    root to: 'pages#home'

    get 'pages/thanks' => 'pages#thanks'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users do
      resources :events, only: [:new, :create]
    end

    get 'events/:id/calendar' => 'events#ics_export'
    get 'events/:id/withdraw' => 'events#withdraw'
    resources :events, only: [:index, :show, :edit, :update, :destroy] do
      resources :bookings, only: [:create, :show] do
        resources :payments, only: [:new, :create]
      end
      resources :messages, only: [:create]
    end

    resources :bookings, only: [:index, :show, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :edit, :update, :destroy]
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:registrations, :sessions]

end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :events, dependent: :nullify
  has_many :messages, dependent: :nullify
  has_many :bookings, dependent: :nullify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :photo, PhotoUploader
  validates :first_name, presence: true, allow_blank: false
  validates :last_name, presence: true, allow_blank: false

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @booking = Booking.new
    @duplicated_event = Event.new
    # Tous les bookings en cours de l'user (yc. lorsqu'il organise ou lorsqu'il est en liste d'attente)
    @all_bookings_active = @user.bookings.joins(:event).where("events.active = ? AND bookings.cancelled = ? AND bookings.state = ?", true, false, 'paid') + @user.bookings.joins(:event).where("events.active = ? AND bookings.cancelled = ? AND bookings.on_waiting_list = ?", true, false, true)
    # Tous les bookings en cours de l'user à venir
    @bookings_active_to_come = @all_bookings_active.select do |booking|
      booking.event.starts_at >= DateTime.now()
    end
    # Tous les bookings en cours de l'user passés
    @bookings_active_past = @all_bookings_active.select do |booking|
      booking.event.starts_at < DateTime.now()
    end
    # Tous les bookings de l'user où l'event a été annulé
    @bookings_event_cancelled = @user.bookings.joins(:event).where("events.active = ?", false)
    # Tous les bookings de l'user où il a annulé sa participation
    @bookings_cancelled = @user.bookings.joins(:event).where("events.active = ? AND bookings.cancelled = ?", true, true)
    # Tous les bookings non archivés
    @bookings_not_archived = @bookings_active_to_come.sort_by { |booking| booking.event.starts_at }
    # Tous les bookings archivés non triés
    @bookings_archived_not_sorted = @bookings_active_past + @bookings_event_cancelled + @bookings_cancelled
    # Tous les bookings archivés triés
    @bookings_archived = @bookings_archived_not_sorted.sort_by { |booking| booking.event.starts_at }
    # Events non annulés organisés par @user triés par dte de création
    @events_organized = @user.events.where("events.active = ?", true).sort_by { |event| event.created_at }
    # Tous les bookings en cours de l'user (hors annulés et liste d'attente)
    @events_participated = @user.bookings.joins(:event).where("events.active = ? AND bookings.cancelled = ? AND bookings.state = ?", true, false, 'paid').sort_by { |event| event.created_at }
  end

  private
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_event-banner-calendar.html.erb
<div class="event-calendar-mq">
  <div class="icon-user-show">
    <i class="fi-calendar"></i>
  </div>
  <div class="item-user-show">
    <div class="half-width">
      <p><strong> <%= t('users.show.event-banner.beginning') %></strong></p>
      <p> <%= event.starts_at.strftime('%d/%m/%Y - %H:%M') %> </p>
    </div>
    <div class="half-width">
      <p><strong> <%= t('users.show.event-banner.end') %></strong></p>
      <p> <%= event.ends_at.strftime('%d/%m/%Y - %H:%M') %> </p>
    </div>
  </div>
</div>

app/views/users/_event-banner-organizer.html.erb
<div class="">
  <!-- Le current user est l'organisateur -->
  <% if current_user == event.user %>
    <!-- L'activité est annulée -->
    <% if event.active == false%>
      <div class="event-organizer-mq text-center">
        <div class="icon-user-show">
          <i class="fi-prohibited"></i>
        </div>
        <div class="item-user-show">
          <p class="red-font half-width"><strong><%= t('users.show.event-banner.cancelled_activity') %></strong></p>
          <div class= "btn-duplicate half-width">
            <%= link_to '#', data: {toggle: "modal", target: "#ModalDupplicate_"+event.id.to_s}, class: "btn btn-danger" do %>
              <%=  t('users.show.event-banner.duplicate')%>
            <% end %>
          </div>
        </div>
      </div>
    <!-- La cagnotte a été collectée -->
    <% elsif event.withdrawed == true %>
      <div class="event-organizer-mq text-center">
        <div class="icon-user-show">
          <i class="fi-checkbox"></i>
        </div>
        <div class="item-user-show">
          <p class="red-font half-width"><strong><%= t('users.show.event-banner.money_collected') %></strong></p>
          <div class= "btn-duplicate half-width">
            <%= link_to '#', data: {toggle: "modal", target: "#ModalDupplicate_"+event.id.to_s}, class: "btn btn-danger" do %>
              <%=  t('users.show.event-banner.duplicate')%>
            <% end %>
          </div>
        </div>
      </div>
    <!-- L'activité est passée -->
    <% elsif Time.now() > event.starts_at%>
      <div class="event-organizer-mq text-center">
        <div class="icon-user-show">
          <i class="fi-clock"></i>
        </div>
        <div class="item-user-show">
          <p class="red-font half-width"><strong><%= t('users.show.event-banner.past_activity') %></strong></p>
          <div class= "btn-duplicate half-width">
            <%= link_to '#', data: {toggle: "modal", target: "#ModalDupplicate_"+event.id.to_s}, class: "btn btn-danger" do %>
              <%=  t('users.show.event-banner.duplicate')%>
            <% end %>
          </div>
        </div>
      </div>
    <!-- L'activité est à venir et non annulée et non collectée -->
    <% else %>
      <div class="event-organizer-mq text-center">
        <div class="icon-user-show">
          <i class="fi-wrench"></i>
        </div>
        <div class="item-user-show">
          <div class = "edit-button half-width">
            <%=link_to t('users.show.event-banner.edit'), edit_event_path(event), class: "btn btn-danger" %>
          </div>
          <div class="delete-link half-width">
            <%= link_to t('users.show.event-banner.delete'), event_path(event), data: { confirm: t('users.show.event-banner.delete-question'), commit: t('users.show.event-banner.delete-yes'), cancel: t('users.show.event-banner.delete-no') }, method: :delete%>
          </div>
        </div>
      </div>
    <% end %>
    <!-- Modal en cas de duplication -->
    <div class="modal fade" id="ModalDupplicate_<%=event.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"> <%= t('events.show.date_pick') %> </h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for [current_user, duplicated_event], method: :post do |f| %>
              <div class="col-xs-6">
                <%= f.input :starts_at, label: false, placeholder: t('events.new.starts_at'), as: :string, input_html: { class: "datetimepicker" } %>
              </div>
              <div class="col-xs-6">
                <%= f.input :ends_at, label: false, placeholder: t('events.new.ends_at'), as: :string, input_html: { class: "datetimepicker" } %>
              </div>
              <%= f.hidden_field :name, value: event.name %>
              <%= f.hidden_field :description, value: event.description %>
              <% if event.max_participants %>
                <%= f.hidden_field :max_participants, value: event.max_participants %>
              <% end %>
              <%= f.hidden_field :price, value: event.price %>
              <% if event.photo %>
                <%= f.hidden_field :photo, value: event.photo %>
                <%= f.hidden_field :photo_cache, value: event.photo_cache %>
              <% end %>
              <%= f.hidden_field :location, value: event.location %>
              <%= f.hidden_field :notif_subscription, value: event.notif_subscription %>
              <%= f.hidden_field :notif_cancellation, value: event.notif_cancellation %>
              <%= f.hidden_field :notif_message, value: event.notif_message %>
              <%= f.submit t('events.show.duplicate_confirm') , class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <!-- Le current user n'est pas l'organisateur -->
  <% else %>
    <!-- L'activité est annulée -->
    <% if event.active == false%>
      <div class="event-organizer-mq text-center">
        <div class="icon-user-show">
          <i class="fi-prohibited"></i>
        </div>
        <div class="item-user-show">
          <p class="red-font"><strong><%= t('users.show.event-banner.cancelled_by', organizer: event.user.first_name) %></strong></p>
        </div>
      </div>
    <!-- L'activité est fermée à l'inscription car collectée -->
    <% elsif event.withdrawed == true %>
      <div class="event-organizer-mq text-center">
        <div class="icon-user-show">
          <i class="fi-checkbox"></i>
        </div>
        <div class="item-user-show">
          <p class="red-font"><strong><%= t('users.show.event-banner.money_collected')%></strong></p>
        </div>
      </div>
    <!-- L'activité est passée -->
    <% elsif Time.now() > event.starts_at %>
      <div class="event-organizer-mq text-center">
        <div class="icon-user-show">
          <i class="fi-clock"></i>
        </div>
        <div class="item-user-show">
          <p class="red-font"><strong><%= t('users.show.event-banner.past_activity') %></strong></p>
        </div>
      </div>
    <!-- L'activité est à venir et non annulée et non collectée -->
    <% else %>
      <div class="event-organizer-mq text-center">
        <!-- Avatar de l'organisateur -->
        <div class="icon-user-show">
          <%= link_to user_path(event.user) do %>
            <div class="event-avatar-mq text-center">
              <p><%= t('users.show.event-banner.organized_by') %> </p>
              <div class="text-center">
                <%= avatar(event.user) %>
              </div>
              <p><strong> <%= event.user.first_name %></strong> </p>
            </div>
          <% end %>
        </div>
        <div class="item-user-show">
          <!-- Le current user a un booking pour l'event -->
          <% if has_a_booking_not_cancelled?(current_user, event) %>
            <% booking = booking_find_by_user_and_event(current_user, event) %>
            <% if booking != "No booking" %>
              <!-- Le booking est validé -->
              <% if booking.on_waiting_list == false && booking.state == 'paid' %>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#ModalUnsubscribe_<%=booking.id%>">
                  <%= t('users.show.event-banner.unsubscribe') %>
                </button>
                <!-- Modal en cas de désinscription -->
                <div class="modal fade" id="ModalUnsubscribe_<%=booking.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><%=  t('users.show.event-banner.sure') %></h4>
                      </div>
                      <div class="modal-body">
                        <%= simple_form_for booking, method: :delete do |f| %>
                          <%= f.input :cancellation_message, label: t('users.show.event-banner.unsubscribe_title', organizer: event.user.first_name) %>
                          <%= f.submit t('users.show.event-banner.send'), class: "btn btn-danger" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <!-- Le current user est en liste d'attente -->
              <% elsif booking.on_waiting_list == true %>
                <p class="red-font margin-top align-left half-width"><%= t('users.show.event-banner.waiting-list-on') %></p>
                <% if event.max_participants - event.validated_bookings_number > 0 %>
                <div class="half-width">
                  <%= simple_form_for booking do |f| %>
                     <%= f.hidden_field :on_waiting_list, value: false %>
                     <%= f.hidden_field :reimbursed, value: "pending" %>
                     <%= f.submit t('users.show.event-banner.participate'), class: "btn btn-danger" %>
                   <% end %>
                </div>
                <% end %>
              <% end %>
            <% end %>
          <!-- Le current user n'a pas encore de booking pour l'event -->
          <% else %>
            <!-- Il reste des places -->
            <% if !event.max_participants? || (event.max_participants - event.validated_bookings_number > 0) %>
              <div >
                <%= simple_form_for [event, @booking], method: :post do |f| %>
                    <%= f.hidden_field :on_waiting_list, value: false %>
                    <%= f.hidden_field :reimbursed, value: "pending" %>
                    <%= f.submit t('users.show.event-banner.participate'), class: "btn btn-danger" %>
                <% end %>
              </div>
            <!-- L'événement est complet -->
            <% else %>
              <div >
                <%= simple_form_for [event, @booking], method: :post do |f| %>
                  <%= f.hidden_field :on_waiting_list, value: true %>
                  <%= f.hidden_field :reimbursed, value: "pending" %>
                  <%= f.submit t('users.show.event-banner.waiting-list-subscribe'), class: "btn btn-danger" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_event-banner-participants.html.erb
<div class="event-participants-mq">
    <div class="icon-user-show">
      <i class="fi-male"></i>
    </div>
    <div class="item-user-show">
      <p class = "half-width"> <strong> <%= t('users.show.event-banner.participants', count: event.validated_bookings_number) %> </strong> </p>
      <% if event.max_participants? %>
        <p class = "half-width"> <%= t('users.show.event-banner.places', count: event.max_participants - event.validated_bookings_number) %> </p>
      <% end %>
    </div>
</div>

app/views/users/_event-banner.html.erb
<div class="event-banner-user-show">
  <div class="container-list">
    <div class="photo-info-box">
      <div class="event-photo-mq">
        <%= link_to event_path(event) do %>
          <div class="margin event-photo" style="background-image: url('<%= url_photo(event) %>');">
          </div>
        <% end %>
      </div>
      <div class="event-box-right">
        <div class="event-title-mq">
          <%= link_to event_path(event) do %>
            <h3 class="border-bottom"> <strong> <%= event.name %> </strong> </h3>
          <% end %>
        </div>
        <div class="top-boxes">
          <div class="calendar">
            <%= render partial: "event-banner-calendar", locals: {event: event} %>
          </div>
          <div class="participants-md-lg">
            <%= render partial: "event-banner-participants", locals: {event: event} %>
          </div>
          <!-- Partie de droite qui dépend de l'organisateur -->
          <div class="organizer-lg">
            <%= render partial: "event-banner-organizer", locals: {event: event, duplicated_event: @duplicated_event} %>
          </div>
        </div>
      </div>
    </div>
    <!-- lien à copier -->
    <div class="event-link-mq text-center">
        <%= render partial: "event-link-banner", locals: {event: event} %>
    </div>
  </div>
</div>

app/views/users/_event-link-banner.html.erb
<div class = "event-link">
  <div class="event-link-url" id="copy_<%=event.id%>"><p id="copy"><%= event_url(event.id) %></p></div>
  <div class="alert-copy-link" id="alert_<%=event.id%>">
    <p><%= t('copy-link.notification') %></p>
  </div>
</div>
<div class="event-link-btn">
  <div class="btn btn-primary btn-copy-link" data-clipboard-target="#copy_<%=event.id%>" id="btn_<%=event.id%>">
    <%= t('users.show.event-banner.event-link-banner.copy') %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="text-center">
    <h2> <%= @user.first_name %> <%= @user.last_name %> </h2>
    <div> <%= avatar_large(@user) %> </div>
  </div>
  <!-- Cas où current user est sur sa propre page de profil -->
  <% if @user == current_user %>
    <div class="text-center">
      <div class="container create-edit-container">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4">
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <%= link_to new_user_event_path(@user) do %>
                <button class = "btn btn-danger"> <%= t('users.show.create')%></button>
              <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 edit-profile-link">
            <%= link_to t('users.show.edit'), edit_user_registration_path, class: "margin margin-sides" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Affichage des events non archivés -->
    <% unless @bookings_not_archived.empty? %>
      <% @bookings_not_archived.each do |booking| %>
        <%= render "event-banner", event: booking.event %>
      <% end %>
    <% end %>
    <!-- Affichage des events archivés -->
    <% unless @bookings_archived.empty? %>
      <div class="archives_button unhide_archives_button"><i class="fi-plus"></i>  <%= t('users.show.unhide_archives')%></div>
      <div class="archives_button hide_archives_button hidden"><i class="fi-minus"></i> <%= t('users.show.hide_archives')%></div>
      <% @bookings_archived.each do |booking| %>
        <div class="archives_banners hidden">
          <%= render "event-banner", event: booking.event %>
        </div>
      <% end %>
    <% end %>
  <!-- Cas où current user est sur la page de profil d'un autre user -->
  <% else %>
    <div class="profile-stats">
      <div class="bandeau-rose">
        <%= t('users.show.on-zadl-since_html', date: time_ago_in_words(@user.created_at))%>
      </div>
      <div class="blocks">
        <div class="block-organizer container-list">
          <h3 class= "border-bottom"> <%= t('users.show.block-organizer-title')%> </h3>
          <div class = "info">
            <div class="icon"><i class="fi-megaphone"></i></div>
            <div> <%= t('users.show.organized-activity_html', count: @events_organized.size)%></div>
          </div>
          <% if @events_organized.size > 0 %>
            <div class = "info">
              <div class="icon"><i class="fi-clock"></i></div>
              <div> <%= t('users.show.last-organized-activity_html', date: time_ago_in_words(@events_organized.last.created_at))%></div>
            </div>
          <% end %>
        </div>
        <div class="block-participant container-list">
          <h3 class= "border-bottom"> <%= t('users.show.block-participant-title')%> </h3>
          <div class = "info">
            <div class="icon"><i class="fi-ticket"></i></div>
            <div> <%= t('users.show.participated-activity_html', count: @events_participated.size)%> </div>
          </div>
          <% if @events_participated.size > 0 %>
            <div class = "info">
              <div class="icon"><i class="fi-clock"></i></div>
              <div> <%= t('users.show.last-participated-activity_html', date: time_ago_in_words(@events_participated.last.created_at))%> </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!-- Hide / Show archives  -->

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      $('.unhide_archives_button').on('click', function() {
        $(this).addClass("hidden");
        $('.hide_archives_button').removeClass("hidden");
        $('.archives_banners').removeClass("hidden");
      })
      $('.hide_archives_button').on('click', function() {
        $(this).addClass("hidden");
        $('.archives_banners').addClass("hidden");
        $('.unhide_archives_button').removeClass("hidden");
      })
    });
  </script>
<% end %>