config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en/ do
    devise_for :users, :controllers => { registrations: 'registrations' }, skip: :omniauth_callbacks

    root to: 'pages#home'

    get 'pages/thanks' => 'pages#thanks'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users do
      resources :events, only: [:new, :create]
    end

    get 'events/:id/calendar' => 'events#ics_export'
    get 'events/:id/withdraw' => 'events#withdraw'
    resources :events, only: [:index, :show, :edit, :update, :destroy] do
      resources :bookings, only: [:create, :show] do
        resources :payments, only: [:new, :create]
      end
      resources :messages, only: [:create]
    end

    resources :bookings, only: [:index, :show, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :edit, :update, :destroy]
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:registrations, :sessions]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-8">
        <ul class="list-inline">
          <li><a class="fi-social-facebook" href=""></a></li>
          <li><a class="fi-social-instagram" href=""></a></li>
          <li><a class="fi-social-twitter" href="https://twitter.com/ZADLLDAZ" target="_blank"></a></li>
        </ul>
      </div>
      <div class="col-xs-4 text-right">
        <p><%= t('footer.about') %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Merci -->
  <div class="container text-center center-button">
    <div>
      <%= link_to pages_thanks_path do %>
      <h1> <i class="thanxbtn fi-heart" aria-hidden="true"></i></h1>
      <% end %>
    </div>
  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right">
    <!-- Language choice -->
    <div>
      <%= link_to locale: nil do %>
        <%= image_tag("France_flag.png", class: "flag")  %>
      <% end %>
    </div>
    <div>
      <%= link_to locale: 'en' do %>
        <%= image_tag("union jack.png", class: "flag") %>
      <% end %>
    </div>

    <!-- Search form -->
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= avatar_dropdown(current_user) %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fi-torso"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fi-home"></i>  <%= t(".profile", default: "Accueil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fi-x"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>
</div>