config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en/ do
    devise_for :users, :controllers => { registrations: 'registrations' }, skip: :omniauth_callbacks

    root to: 'pages#home'

    get 'pages/thanks' => 'pages#thanks'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users do
      resources :events, only: [:new, :create]
    end

    get 'events/:id/calendar' => 'events#ics_export'
    get 'events/:id/withdraw' => 'events#withdraw'
    resources :events, only: [:index, :show, :edit, :update, :destroy] do
      resources :bookings, only: [:create, :show] do
        resources :payments, only: [:new, :create]
      end
      resources :messages, only: [:create]
    end

    resources :bookings, only: [:index, :show, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :edit, :update, :destroy]
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:registrations, :sessions]

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_booking
  before_action :set_event

  def new
    authorize @booking
  end

  def create
    stripe_customer_id = current_user.stripe_customer_id

    unless stripe_customer_id
      customer = Stripe::Customer.create(
       source: params[:stripeToken],
       email:  params[:stripeEmail]
      )

      stripe_customer_id = customer.id
      current_user.update(stripe_customer_id: stripe_customer_id)
    end

    charge = Stripe::Charge.create(
     customer:     stripe_customer_id,
     amount:       @booking.amount_cents, # or amount_pennies
     description:  t('controllers.payments.payment', activity = @booking.event.name),
     currency:     @booking.amount.currency
    )
    authorize @booking


    @booking.update(payment: charge.to_json, state: 'paid')
    if @event.notif_subscription
      BookingMailer.user_subscription(current_user,@event).deliver_now
    end
    flash[:notice] = t('controllers.payments.confirmation')
    redirect_to event_path(@event)

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_event_booking_payment_path(@event, @booking)
  end

  private

  def set_booking
    @booking = Booking.where(state: "pending").find(params[:booking_id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class="form-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="form-container">
          <div class="form-part-title"> <%= t('payments.new.title') %></div>
          <div class="description-payment">
            <h5><%= t('payments.new.activity_html', activity: @booking.event.name) %></h5>
            <h5><%= t('payments.new.organized_by_html', organizer: @booking.event.user.first_name) %></h5>
            <h5>
              <%= t('payments.new.start_html', start: @booking.event.starts_at.strftime('%d/%m/%Y - %H:%M')) %>
            </h5>
          </div>
          <%= form_tag event_booking_payments_path(@event, @booking) do %>
            <article>
              <label class="amount">
                <span><%= t('payments.new.price', price: @booking.amount) %> € </span>
              </label>
            </article>

            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-name="Mon activité"
              data-email="<%= current_user.email %>"
              data-description="Activité <%= @booking.event.name %>"
              data-amount="<%= @booking.amount_cents %>"
              data-currency="<%= @booking.amount.currency %>">
            </script>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>