config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en/ do
    devise_for :users, :controllers => { registrations: 'registrations' }, skip: :omniauth_callbacks

    root to: 'pages#home'

    get 'pages/thanks' => 'pages#thanks'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users do
      resources :events, only: [:new, :create]
    end

    get 'events/:id/calendar' => 'events#ics_export'
    get 'events/:id/withdraw' => 'events#withdraw'
    resources :events, only: [:index, :show, :edit, :update, :destroy] do
      resources :bookings, only: [:create, :show] do
        resources :payments, only: [:new, :create]
      end
      resources :messages, only: [:create]
    end

    resources :bookings, only: [:index, :show, :edit, :update, :destroy]
    resources :messages, only: [:index, :show, :edit, :update, :destroy]
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:registrations, :sessions]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZADL</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.png' %>

  <!-- Meta tags-->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta property="fb:app_id" content="1329301247112385"/>

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">
  </head>
  <body class="<%= "#{controller_path}-#{action_name}" %>">
   <div class="wrapper">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>


    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>

    <%= yield(:after_js) %>
  </body>
</html>